version: 2

jobs:
  build:
    docker:
      - image: msvrtan/square:0.2.2
        environment:
          - APP_ENV=test
          - APP_DEBUG=1
          - APP_SECRET=123
    working_directory: /var/www
    parallel: 1
    steps:
      - checkout

      - restore_cache:
          key: cache-v1-{{ checksum "composer.lock" }}

      - run:
          name: Disable xdebug
          command: ./etc/circleci2/disable-xdebug.sh

      - run:
          name: Composer install
          command: SYMFONY_ENV=test composer install --prefer-dist --no-interaction

      - run:
          name: Lint all PHP code files # runs lint only on php files in feature/src/spec/tests folder that are changed since 2017-12-03 (uses hash to determine commit from which to start check)
          command: git diff --name-only --diff-filter=ACMR 6836d6eb5692fd5bea5f3613bfd47ba276a16d53 | grep -E "^(feature|src|spec|tests)\/.*php$" | xargs -n1 php -l 1> /dev/null

      - run:
          name: PHPSpec
          command: ./vendor/bin/phpspec run

      - run:
          name: PHPUnit
          command: ./vendor/bin/phpunit

      - run:
          name: PHPStan
          command: ./vendor/bin/phing phpstan

      - run:
          name: Code standards
          command: ./vendor/bin/phing check-codestandards

      - save_cache:
          key: cache-v1-{{ checksum "composer.lock" }}
          paths:
            - /var/www/vendor

      - store_artifacts:
          path: build
          destination: build

  humbug:
    docker:
      - image: msvrtan/square:0.2.2
        environment:
          - APP_ENV=test
          - APP_DEBUG=1
          - APP_SECRET=123
    working_directory: /var/www
    parallel: 1
    steps:
      - checkout

      - restore_cache:
          key: cache-v1-{{ checksum "composer.lock" }}

      - run:
          name: Composer install
          command: SYMFONY_ENV=test composer install --prefer-dist --no-interaction

      - run:
          name: Humbug
          command: ./vendor/bin/humbug

      - store_artifacts:
          path: build
          destination: build

  codecoverage_phpunit:
    docker:
      - image: msvrtan/square:0.2.2
        environment:
          - APP_ENV=test
          - APP_DEBUG=1
          - APP_SECRET=123
    working_directory: /var/www
    parallel: 1
    steps:
      - checkout

      - restore_cache:
          key: cache-v1-{{ checksum "composer.lock" }}

      - run:
          name: Composer install
          command: SYMFONY_ENV=test composer install --prefer-dist --no-interaction

      - run:
          name: PHPUnit
          command: ./vendor/bin/phpunit

      - run:
          name: Ship codecoverage to codecov.io
          command: bash <(curl -s https://codecov.io/bash)

      - store_artifacts:
          path: build
          destination: build

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - humbug
      - codecoverage_phpunit
