# j2c


./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/Definition/TestDateTimeValueObject'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/Definition/TestSimpleEntity'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/Definition/TestSimpleIdentifier'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/Definition/TestSingleValueObject'

./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/DefinitionFactory/TestDateTimeValueObjectFactory'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/DefinitionFactory/TestSimpleEntityFactory'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/DefinitionFactory/TestSimpleIdentifierFactory'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/DefinitionFactory/TestSingleValueObjectFactory'

./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/DefinitionGenerator/TestDateTimeValueObjectGenerator'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/DefinitionGenerator/TestSimpleEntityGenerator'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/DefinitionGenerator/TestSimpleIdentifierGenerator'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/DefinitionGenerator/TestSingleValueObjectGenerator'

./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/DefinitionMiddleware/TestDateTimeValueObjectMiddleware'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/DefinitionMiddleware/TestSimpleEntityMiddleware'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/DefinitionMiddleware/TestSimpleIdentifierMiddleware'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/DefinitionMiddleware/TestSingleValueObjectMiddleware'

./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/Method/BaseTestMethod'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/Method/TestGetterMethod'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/Method/SetUpMethod'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/Method/TestDateTimeCreateFromFormatMethod'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/Method/TestDateTimeDeserializeMethod'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/Method/TestDateTimeSetUpMethod'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/Method/TestDateTimeSerializeMethod'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/Method/TestDateTimeToStringMethod'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/Method/TestDeserializeMethod'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/Method/TestSerializeMethod'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/Method/TestToStringMethod'

./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/MethodFactory/TestGetterMethodFactory'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/MethodFactory/SetUpMethodFactory'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/MethodFactory/TestDateTimeCreateFromFormatMethodFactory'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/MethodFactory/TestDateTimeDeserializeMethodFactory'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/MethodFactory/TestDateTimeSetUpMethodFactory'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/MethodFactory/TestDateTimeSerializeMethodFactory'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/MethodFactory/TestDateTimeToStringMethodFactory'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/MethodFactory/TestDeserializeMethodFactory'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/MethodFactory/TestSerializeMethodFactory'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/MethodFactory/TestToStringMethodFactory'

./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/MethodGenerator/TestGetterMethodGenerator'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/MethodGenerator/SetUpMethodGenerator'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/MethodGenerator/TestDateTimeCreateFromFormatMethodGenerator'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/MethodGenerator/TestDateTimeDeserializeMethodGenerator'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/MethodGenerator/TestDateTimeSetUpMethodGenerator'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/MethodGenerator/TestDateTimeSerializeMethodGenerator'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/MethodGenerator/TestDateTimeToStringMethodGenerator'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/MethodGenerator/TestDeserializeMethodGenerator'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/MethodGenerator/TestSerializeMethodGenerator'
./vendor/bin/phpspec desc 'NullDevelopment/Skeleton/PhpUnit/MethodGenerator/TestToStringMethodGenerator'