definition:
  type: SimpleIdentifier
  className: MyVendor\Product\ProductId
  parent: ~
  interfaces: []
  traits: []
  constructor:
    id:
      className: int
      nullable: false
      hasDefault: false
      default: ~