definition:
  type: SimpleEntity
  className: MyVendor\ProductEntity
  parent: ~
  interfaces: []
  traits: []
  constructor:
    id:
      className: MyVendor\Product\ProductId
      nullable: false
      hasDefault: false
      default: ~
    title:
      className: string
      nullable: false
      hasDefault: false
      default: ~
    description:
      className: string
      nullable: true
      hasDefault: false
      default: ~
    weight:
      className: MyVendor\Product\ProductWeight
      nullable: true
      hasDefault: false
      default: ~
    updatedAt:
      className: DateTime
      nullable: false
      hasDefault: false
      default: ~