parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true


  #
  #
  # Source code

  NullDevelopment\Skeleton\SourceCode\DefinitionGenerator\SingleValueObjectGenerator:
    arguments:
      $methodGenerators:
        - '@NullDevelopment\Skeleton\SourceCode\MethodGenerator\ConstructorMethodGenerator'
        - '@NullDevelopment\Skeleton\SourceCode\MethodGenerator\GetterMethodGenerator'
        - '@NullDevelopment\Skeleton\SourceCode\MethodGenerator\ToStringMethodGenerator'
        - '@NullDevelopment\Skeleton\SourceCode\MethodGenerator\SerializeMethodGenerator'
        - '@NullDevelopment\Skeleton\SourceCode\MethodGenerator\DeserializeMethodGenerator'
    tags:
      - { name: tactician.handler, command: 'NullDevelopment\Skeleton\SourceCode\Definition\SingleValueObject' }

  NullDevelopment\Skeleton\SourceCode\MethodGenerator\ConstructorMethodGenerator: ~
  NullDevelopment\Skeleton\SourceCode\MethodGenerator\GetterMethodGenerator: ~
  NullDevelopment\Skeleton\SourceCode\MethodGenerator\ToStringMethodGenerator: ~
  NullDevelopment\Skeleton\SourceCode\MethodGenerator\SetterMethodGenerator: ~
  NullDevelopment\Skeleton\SourceCode\MethodGenerator\SerializeMethodGenerator: ~
  NullDevelopment\Skeleton\SourceCode\MethodGenerator\DeserializeMethodGenerator: ~

  NullDevelopment\Skeleton\SourceCode\DefinitionLoaderCollection:
    arguments:
      $loaders:
        - '@NullDevelopment\Skeleton\SourceCode\DefinitionLoader\SingleValueObjectLoader'

  NullDevelopment\Skeleton\SourceCode\DefinitionLoader\SingleValueObjectLoader: ~

  NullDevelopment\Skeleton\SourceCode\DefinitionLoader\Factory\ConstructorMethodFactory: ~
  NullDevelopment\Skeleton\SourceCode\DefinitionLoader\Factory\InterfaceNameCollectionFactory: ~
  NullDevelopment\Skeleton\SourceCode\DefinitionLoader\Factory\PropertyCollectionFactory: ~
  NullDevelopment\Skeleton\SourceCode\DefinitionLoader\Factory\TraitNameCollectionFactory: ~





  #
  #
  #PhpSpec

  NullDevelopment\Skeleton\PhpSpec\DefinitionGenerator\SpecSingleValueObjectGenerator:
    arguments:
      $methodGenerators:
        - '@NullDevelopment\Skeleton\PhpSpec\MethodGenerator\LetMethodGenerator'
        - '@NullDevelopment\Skeleton\PhpSpec\MethodGenerator\InitializableMethodGenerator'
        - '@NullDevelopment\Skeleton\PhpSpec\MethodGenerator\GetterSpecMethodGenerator'
        - '@NullDevelopment\Skeleton\PhpSpec\MethodGenerator\SpecToStringMethodGenerator'
        - '@NullDevelopment\Skeleton\PhpSpec\MethodGenerator\SpecSerializeMethodGenerator'
        - '@NullDevelopment\Skeleton\PhpSpec\MethodGenerator\SpecDeserializeMethodGenerator'

  NullDevelopment\Skeleton\PhpSpec\DefinitionFactory\SpecSingleValueObjectFactory:
    arguments:
      $factories:
        - '@NullDevelopment\Skeleton\PhpSpec\MethodFactory\LetMethodFactory'
        - '@NullDevelopment\Skeleton\PhpSpec\MethodFactory\InitializableMethodFactory'
        - '@NullDevelopment\Skeleton\PhpSpec\MethodFactory\GetterSpecMethodFactory'
        - '@NullDevelopment\Skeleton\PhpSpec\MethodFactory\SpecToStringMethodFactory'
        - '@NullDevelopment\Skeleton\PhpSpec\MethodFactory\SpecSerializeMethodFactory'
        - '@NullDevelopment\Skeleton\PhpSpec\MethodFactory\SpecDeserializeMethodFactory'

  NullDevelopment\Skeleton\PhpSpec\MethodGenerator\LetMethodGenerator: ~
  NullDevelopment\Skeleton\PhpSpec\MethodGenerator\InitializableMethodGenerator: ~
  NullDevelopment\Skeleton\PhpSpec\MethodGenerator\GetterSpecMethodGenerator: ~
  NullDevelopment\Skeleton\PhpSpec\MethodGenerator\SpecToStringMethodGenerator: ~
  NullDevelopment\Skeleton\PhpSpec\MethodGenerator\SpecSerializeMethodGenerator: ~
  NullDevelopment\Skeleton\PhpSpec\MethodGenerator\SpecDeserializeMethodGenerator: ~

  NullDevelopment\Skeleton\PhpSpec\MethodFactory\LetMethodFactory: ~
  NullDevelopment\Skeleton\PhpSpec\MethodFactory\InitializableMethodFactory: ~
  NullDevelopment\Skeleton\PhpSpec\MethodFactory\GetterSpecMethodFactory: ~
  NullDevelopment\Skeleton\PhpSpec\MethodFactory\SpecToStringMethodFactory: ~
  NullDevelopment\Skeleton\PhpSpec\MethodFactory\SpecSerializeMethodFactory: ~
  NullDevelopment\Skeleton\PhpSpec\MethodFactory\SpecDeserializeMethodFactory: ~


  NullDevelopment\Skeleton\PhpSpec\DefinitionMiddleware\SpecSingleValueObjectMiddleware:
    tags:
      - { name: tactician.middleware , priority: 50 }



  #
  #
  #Misc
  NullDevelopment\Skeleton\ExampleMaker\ExampleMaker: ~
  NullDevelopment\Skeleton\Path\Readers\FinderFactory: ~
  Symfony\Component\Filesystem\Filesystem: ~


  NullDevelopment\Skeleton\File\FileFactory: ~
  NullDevelopment\Nemesis\Config\ConfigFactory: ~

  NullDevelopment\Nemesis\Config\Config:
    class: NullDevelopment\Nemesis\Config\Config
    factory: ['@NullDevelopment\Nemesis\Config\ConfigFactory', create]


